/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.CitaBO;
import BO.PacienteBO;
import DTO.CitaDTO;
import configuracion.DependencyInjector;
import excepciones.NegocioException;
import java.time.LocalDateTime;
import java.util.Comparator;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sesion.ManejadorSesion;

/**
 *
 * @author Alici
 */
public class FrmCitasMedico extends javax.swing.JFrame {

    private CitaBO citaBO = DependencyInjector.crearCitaBO();
    private PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();
    private List<CitaDTO> citasPrevias;
    private List<CitaDTO> citasEmergencia;
    Timer timer = new Timer();

    /**
     * Creates new form FrmCitas
     */
    public FrmCitasMedico() {
        initComponents();
//        cargarCitasPrevias();
//        cargarCitasEmergencia();
            tablaCitasEmergencia.removeColumn(tablaCitasEmergencia.getColumnModel().getColumn(0));
            tablaCitas.removeColumn(tablaCitas.getColumnModel().getColumn(0));

        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                cargarCitasPrevias();
                cargarCitasEmergencia();
            }
        }, 0, 60000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraLateral = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        btnActivarCuenta = new javax.swing.JButton();
        btnConsultaPrevia = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        lblCerrarSesion = new javax.swing.JLabel();
        btnBajaTemporal = new javax.swing.JButton();
        panelRedondoCitasP = new GUI.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        lblCitasProximas = new javax.swing.JLabel();
        btnAtenderCitaProxima = new javax.swing.JButton();
        panelRedondoCitasE = new GUI.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCitasEmergencia = new javax.swing.JTable();
        lblCitasEmergencia = new javax.swing.JLabel();
        btnAtenderCitaEmergencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(241, 243, 245));
        setResizable(false);
        setSize(new java.awt.Dimension(844, 579));

        panelBarraLateral.setBackground(new java.awt.Color(103, 172, 244));

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatar.png"))); // NOI18N
        lblAvatar.setPreferredSize(new java.awt.Dimension(30, 30));

        btnActivarCuenta.setText("Activar cuenta");
        btnActivarCuenta.setBackground(new java.awt.Color(128, 204, 43));
        btnActivarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnActivarCuenta.setMaximumSize(new java.awt.Dimension(72, 23));
        btnActivarCuenta.setMinimumSize(new java.awt.Dimension(72, 23));
        btnActivarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarCuentaActionPerformed(evt);
            }
        });

        btnConsultaPrevia.setText("Consultas previas");
        btnConsultaPrevia.setBackground(new java.awt.Color(30, 98, 159));
        btnConsultaPrevia.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaPreviaActionPerformed(evt);
            }
        });

        btnCitas.setText("Citas");
        btnCitas.setBackground(new java.awt.Color(30, 98, 159));
        btnCitas.setForeground(new java.awt.Color(255, 255, 255));
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        lblCerrarSesion.setText("<html><u>Cerrar Sesión</u></html>");

        btnBajaTemporal.setText("Baja temporal");
        btnBajaTemporal.setBackground(new java.awt.Color(195, 54, 29));
        btnBajaTemporal.setForeground(new java.awt.Color(255, 255, 255));
        btnBajaTemporal.setMaximumSize(new java.awt.Dimension(72, 23));
        btnBajaTemporal.setMinimumSize(new java.awt.Dimension(72, 23));
        btnBajaTemporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaTemporalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBarraLateralLayout = new javax.swing.GroupLayout(panelBarraLateral);
        panelBarraLateral.setLayout(panelBarraLateralLayout);
        panelBarraLateralLayout.setHorizontalGroup(
            panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConsultaPrevia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBarraLateralLayout.createSequentialGroup()
                        .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActivarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btnBajaTemporal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarraLateralLayout.setVerticalGroup(
            panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCitas)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaPrevia)
                .addGap(18, 18, 18)
                .addComponent(btnBajaTemporal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActivarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelRedondoCitasP.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondoCitasP.setRoundBottomLeft(30);
        panelRedondoCitasP.setRoundBottomRight(30);
        panelRedondoCitasP.setRoundTopLeft(30);
        panelRedondoCitasP.setRoundTopRight(30);

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdCita", "Fecha y hora", "Paciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCitas);
        if (tablaCitas.getColumnModel().getColumnCount() > 0) {
            tablaCitas.getColumnModel().getColumn(0).setResizable(false);
            tablaCitas.getColumnModel().getColumn(1).setResizable(false);
            tablaCitas.getColumnModel().getColumn(2).setResizable(false);
        }

        lblCitasProximas.setText("Citas próximas");
        lblCitasProximas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnAtenderCitaProxima.setText("Atender cita");
        btnAtenderCitaProxima.setBackground(new java.awt.Color(128, 204, 43));
        btnAtenderCitaProxima.setForeground(new java.awt.Color(255, 255, 255));
        btnAtenderCitaProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderCitaProximaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRedondoCitasPLayout = new javax.swing.GroupLayout(panelRedondoCitasP);
        panelRedondoCitasP.setLayout(panelRedondoCitasPLayout);
        panelRedondoCitasPLayout.setHorizontalGroup(
            panelRedondoCitasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoCitasPLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelRedondoCitasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtenderCitaProxima)
                    .addGroup(panelRedondoCitasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCitasProximas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRedondoCitasPLayout.setVerticalGroup(
            panelRedondoCitasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondoCitasPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblCitasProximas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtenderCitaProxima)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelRedondoCitasE.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondoCitasE.setRoundBottomLeft(30);
        panelRedondoCitasE.setRoundBottomRight(30);
        panelRedondoCitasE.setRoundTopLeft(30);
        panelRedondoCitasE.setRoundTopRight(30);

        tablaCitasEmergencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idCita", "Fecha y hora", "Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitasEmergencia.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaCitasEmergencia);
        if (tablaCitasEmergencia.getColumnModel().getColumnCount() > 0) {
            tablaCitasEmergencia.getColumnModel().getColumn(0).setResizable(false);
            tablaCitasEmergencia.getColumnModel().getColumn(1).setResizable(false);
            tablaCitasEmergencia.getColumnModel().getColumn(2).setResizable(false);
        }

        lblCitasEmergencia.setText("Citas emergencia");
        lblCitasEmergencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnAtenderCitaEmergencia.setText("Atender cita");
        btnAtenderCitaEmergencia.setBackground(new java.awt.Color(128, 204, 43));
        btnAtenderCitaEmergencia.setForeground(new java.awt.Color(255, 255, 255));
        btnAtenderCitaEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderCitaEmergenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRedondoCitasELayout = new javax.swing.GroupLayout(panelRedondoCitasE);
        panelRedondoCitasE.setLayout(panelRedondoCitasELayout);
        panelRedondoCitasELayout.setHorizontalGroup(
            panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoCitasELayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtenderCitaEmergencia)
                    .addGroup(panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCitasEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelRedondoCitasELayout.setVerticalGroup(
            panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondoCitasELayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblCitasEmergencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtenderCitaEmergencia)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRedondoCitasE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRedondoCitasP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelRedondoCitasE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRedondoCitasP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivarCuentaActionPerformed

    private void btnConsultaPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaPreviaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaPreviaActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnBajaTemporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaTemporalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaTemporalActionPerformed

    private void btnAtenderCitaEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderCitaEmergenciaActionPerformed
        atenderCita(obtenerIdCitaSeleccionadaCitasEmergencia());
    }//GEN-LAST:event_btnAtenderCitaEmergenciaActionPerformed

    private void btnAtenderCitaProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderCitaProximaActionPerformed
        atenderCita(obtenerIdCitaSeleccionadaCitasPrevias());
    }//GEN-LAST:event_btnAtenderCitaProximaActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmCitasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmCitasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmCitasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmCitasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmCitasMedico().setVisible(true);
//            }
//        });
//    }
    public void cargarCitasPrevias() {
        DefaultTableModel modeloTablaPrevias = (DefaultTableModel) tablaCitas.getModel();
        modeloTablaPrevias.setRowCount(0); // Limpiar la tabla

        try {
            List<CitaDTO> citasPrevias = citaBO.citasActivasMedico(ManejadorSesion.getIdUsuario()).stream().filter(citaDTO -> citaDTO.getTipo().equals("previa")).sorted(Comparator.comparing(CitaDTO::getFechaHora)).toList();

            // Ocultar columna ID

            for (CitaDTO cita : citasPrevias) {

                modeloTablaPrevias.addRow(new Object[]{
                    cita.getIDCita(), // Columna 0 oculta 
                    String.valueOf(cita.getFechaHora().toLocalDate().toString() + " " + cita.getFechaHora().toLocalTime()), // Columna 1 visible
                    String.valueOf(cita.getPacienteSimpleDTO()) // Columna 2 visible
                });
            }

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void cargarCitasEmergencia() {
        DefaultTableModel modeloTablaEmergencia = (DefaultTableModel) tablaCitasEmergencia.getModel();
        modeloTablaEmergencia.setRowCount(0); // Limpiar la tabla

        try {
            List<CitaDTO> citasEmergencia = citaBO.citasActivasMedico(ManejadorSesion.getIdUsuario()).stream().filter(citaDTO -> citaDTO.getTipo().equals("emergencia")).sorted(Comparator.comparing(CitaDTO::getFechaHora)).toList();

            // Tabla de citas de emergencia
            for (CitaDTO cita : citasEmergencia) {
                modeloTablaEmergencia.addRow(new Object[]{
                    cita.getIDCita(),
                    String.valueOf(cita.getFechaHora().toLocalDate().toString() + " " + cita.getFechaHora().toLocalTime()),
                    String.valueOf(cita.getPacienteSimpleDTO())
                });
            }

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void atenderCita(String filaseleccionada) {
        if (filaseleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione la cita a atender", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                CitaDTO citaDTO = citaBO.obtenerCitaPorId(filaseleccionada);
                if (LocalDateTime.now().isBefore(citaDTO.getFechaHora())) {
                    JOptionPane.showMessageDialog(null, "Espere a que sea la hora de la cita", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    FrmRegistrarConsulta frmRegistrarConsulta = new FrmRegistrarConsulta(citaDTO);
                    frmRegistrarConsulta.setVisible(true);
                    dispose();
                }
            } catch (NegocioException ex) {
                Logger.getLogger(FrmRegistrarConsulta.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Método para obtener el ID de la cita al seleccionar una fila
    public String obtenerIdCitaSeleccionadaCitasPrevias() {
        int filaSeleccionada = tablaCitas.getSelectedRow();
        if (filaSeleccionada != -1) {
            return tablaCitas.getModel().getValueAt(filaSeleccionada, 0).toString();
        }
        return null;
    }

    public String obtenerIdCitaSeleccionadaCitasEmergencia() {
        int filaSeleccionada = tablaCitasEmergencia.getSelectedRow();
        if (filaSeleccionada != -1) {
            return tablaCitasEmergencia.getModel().getValueAt(filaSeleccionada, 0).toString();
        }
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarCuenta;
    private javax.swing.JButton btnAtenderCitaEmergencia;
    private javax.swing.JButton btnAtenderCitaProxima;
    private javax.swing.JButton btnBajaTemporal;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnConsultaPrevia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblCitasEmergencia;
    private javax.swing.JLabel lblCitasProximas;
    private javax.swing.JPanel panelBarraLateral;
    private GUI.PanelRound panelRedondoCitasE;
    private GUI.PanelRound panelRedondoCitasP;
    private javax.swing.JTable tablaCitas;
    private javax.swing.JTable tablaCitasEmergencia;
    // End of variables declaration//GEN-END:variables
}
