/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.MedicoBO;
import configuracion.DependencyInjector;
import excepciones.NegocioException;
import java.awt.Color;
import javax.swing.JOptionPane;
import sesion.ManejadorSesion;

/**
 *
 * @author Alici
 */
public class FrmCitasMedico extends javax.swing.JFrame {

    private MedicoBO medicoBO = DependencyInjector.crearMedicoBO();
    /**
     * Creates new form FrmCitas
     */
    public FrmCitasMedico() {
        initComponents();
        cargarNombreMedico();
        cargarEstadoMedicoYActualizarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraLateral = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        btnActivarCuenta = new javax.swing.JButton();
        btnConsultaPrevia = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        lblCerrarSesion = new javax.swing.JLabel();
        btnBajaTemporal = new javax.swing.JButton();
        lblNombreCompletoMedico = new javax.swing.JLabel();
        panelRedondoCitasP = new GUI.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        lblCitasProximas = new javax.swing.JLabel();
        btnAtenderCitaProxima = new javax.swing.JButton();
        panelRedondoCitasE = new GUI.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCitasEmergencia = new javax.swing.JTable();
        lblCitasEmergencia = new javax.swing.JLabel();
        btnGenerarConsulta1 = new javax.swing.JButton();
        btnAtenderCitaEmergencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(241, 243, 245));
        setResizable(false);
        setSize(new java.awt.Dimension(844, 579));

        panelBarraLateral.setBackground(new java.awt.Color(103, 172, 244));

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatar.png"))); // NOI18N
        lblAvatar.setPreferredSize(new java.awt.Dimension(30, 30));

        btnActivarCuenta.setBackground(new java.awt.Color(128, 204, 43));
        btnActivarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnActivarCuenta.setText("Activar cuenta");
        btnActivarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivarCuentaMouseClicked(evt);
            }
        });
        btnActivarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarCuentaActionPerformed(evt);
            }
        });

        btnConsultaPrevia.setBackground(new java.awt.Color(30, 98, 159));
        btnConsultaPrevia.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaPrevia.setText("Consultas previas");
        btnConsultaPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaPreviaActionPerformed(evt);
            }
        });

        btnCitas.setBackground(new java.awt.Color(30, 98, 159));
        btnCitas.setForeground(new java.awt.Color(255, 255, 255));
        btnCitas.setText("Citas");
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        lblCerrarSesion.setText("<html><u>Cerrar Sesión</u></html>");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });

        btnBajaTemporal.setBackground(new java.awt.Color(195, 54, 29));
        btnBajaTemporal.setForeground(new java.awt.Color(255, 255, 255));
        btnBajaTemporal.setText("Baja temporal");
        btnBajaTemporal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBajaTemporalMouseClicked(evt);
            }
        });
        btnBajaTemporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaTemporalActionPerformed(evt);
            }
        });

        lblNombreCompletoMedico.setText("jLabel1");

        javax.swing.GroupLayout panelBarraLateralLayout = new javax.swing.GroupLayout(panelBarraLateral);
        panelBarraLateral.setLayout(panelBarraLateralLayout);
        panelBarraLateralLayout.setHorizontalGroup(
            panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBajaTemporal, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btnActivarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLateralLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBarraLateralLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreCompletoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnConsultaPrevia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(panelBarraLateralLayout.createSequentialGroup()
                        .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelBarraLateralLayout.setVerticalGroup(
            panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreCompletoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCitas)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaPrevia)
                .addGap(18, 18, 18)
                .addComponent(btnBajaTemporal)
                .addGap(18, 18, 18)
                .addComponent(btnActivarCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelRedondoCitasP.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondoCitasP.setRoundBottomLeft(30);
        panelRedondoCitasP.setRoundBottomRight(30);
        panelRedondoCitasP.setRoundTopLeft(30);
        panelRedondoCitasP.setRoundTopRight(30);

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha y hora", "Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCitas);
        if (tablaCitas.getColumnModel().getColumnCount() > 0) {
            tablaCitas.getColumnModel().getColumn(0).setResizable(false);
            tablaCitas.getColumnModel().getColumn(1).setResizable(false);
        }

        lblCitasProximas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCitasProximas.setText("Citas próximas");

        btnAtenderCitaProxima.setBackground(new java.awt.Color(128, 204, 43));
        btnAtenderCitaProxima.setForeground(new java.awt.Color(255, 255, 255));
        btnAtenderCitaProxima.setText("Atender cita");
        btnAtenderCitaProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderCitaProximaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRedondoCitasPLayout = new javax.swing.GroupLayout(panelRedondoCitasP);
        panelRedondoCitasP.setLayout(panelRedondoCitasPLayout);
        panelRedondoCitasPLayout.setHorizontalGroup(
            panelRedondoCitasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoCitasPLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelRedondoCitasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtenderCitaProxima)
                    .addGroup(panelRedondoCitasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCitasProximas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRedondoCitasPLayout.setVerticalGroup(
            panelRedondoCitasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondoCitasPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblCitasProximas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtenderCitaProxima)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelRedondoCitasE.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondoCitasE.setRoundBottomLeft(30);
        panelRedondoCitasE.setRoundBottomRight(30);
        panelRedondoCitasE.setRoundTopLeft(30);
        panelRedondoCitasE.setRoundTopRight(30);

        tablaCitasEmergencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha y hora", "Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCitasEmergencia.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaCitasEmergencia);
        if (tablaCitasEmergencia.getColumnModel().getColumnCount() > 0) {
            tablaCitasEmergencia.getColumnModel().getColumn(0).setResizable(false);
            tablaCitasEmergencia.getColumnModel().getColumn(1).setResizable(false);
        }

        lblCitasEmergencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCitasEmergencia.setText("Citas emergencia");

        btnGenerarConsulta1.setBackground(new java.awt.Color(128, 204, 43));
        btnGenerarConsulta1.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarConsulta1.setText("Activar cuenta");
        btnGenerarConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarConsulta1ActionPerformed(evt);
            }
        });

        btnAtenderCitaEmergencia.setBackground(new java.awt.Color(128, 204, 43));
        btnAtenderCitaEmergencia.setForeground(new java.awt.Color(255, 255, 255));
        btnAtenderCitaEmergencia.setText("Atender cita");
        btnAtenderCitaEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderCitaEmergenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRedondoCitasELayout = new javax.swing.GroupLayout(panelRedondoCitasE);
        panelRedondoCitasE.setLayout(panelRedondoCitasELayout);
        panelRedondoCitasELayout.setHorizontalGroup(
            panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoCitasELayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtenderCitaEmergencia)
                    .addGroup(panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCitasEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondoCitasELayout.createSequentialGroup()
                    .addGap(281, 281, 281)
                    .addComponent(btnGenerarConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(281, Short.MAX_VALUE)))
        );
        panelRedondoCitasELayout.setVerticalGroup(
            panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondoCitasELayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblCitasEmergencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtenderCitaEmergencia)
                .addGap(11, 11, 11))
            .addGroup(panelRedondoCitasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondoCitasELayout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(btnGenerarConsulta1)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRedondoCitasE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRedondoCitasP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelRedondoCitasE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRedondoCitasP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarCuentaActionPerformed
activarCuenta();    }//GEN-LAST:event_btnActivarCuentaActionPerformed

    private void btnConsultaPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaPreviaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaPreviaActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnGenerarConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarConsulta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarConsulta1ActionPerformed

    private void btnBajaTemporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaTemporalActionPerformed
    }//GEN-LAST:event_btnBajaTemporalActionPerformed

    private void btnAtenderCitaEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderCitaEmergenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtenderCitaEmergenciaActionPerformed

    private void btnAtenderCitaProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderCitaProximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtenderCitaProximaActionPerformed

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        cerrarSesion();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        lblCerrarSesion.setForeground(new Color(30, 98, 159));
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        lblCerrarSesion.setForeground(new Color(0, 0,0));
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    private void btnBajaTemporalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBajaTemporalMouseClicked
     bajaCuenta();    }//GEN-LAST:event_btnBajaTemporalMouseClicked

    private void btnActivarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivarCuentaMouseClicked
        activarCuenta ();
    }//GEN-LAST:event_btnActivarCuentaMouseClicked
   
    private void cargarNombreMedico() {
    try {
        String idUsuario = ManejadorSesion.getIdUsuario();
        int idMedico = Integer.parseInt(idUsuario);
        String nombreCompleto = medicoBO.obtenerNombreCompletoMedico(idMedico);
        lblNombreCompletoMedico.setText(nombreCompleto);
    } catch (NegocioException e) {
       
    }
    
}
    private void cerrarSesion() {
        ManejadorSesion.borrarDatosSesion();
        FrmInicioSesion frmInicio = new FrmInicioSesion(); 
        frmInicio.setVisible(true);
        this.dispose();
    }
    
    private void cargarEstadoMedicoYActualizarBotones() {
    try {
        String idUsuario = ManejadorSesion.getIdUsuario();
        int idMedico = Integer.parseInt(idUsuario);
        String estadoMedico = medicoBO.obtenerEstadoMedico(idMedico);

        // Habilitar o deshabilitar botones según el estado
        if (estadoMedico.equals("activo")) {
            btnBajaTemporal.setEnabled(true);
            btnActivarCuenta.setEnabled(false);
        } else if (estadoMedico.equals("inactivo")) {
            btnBajaTemporal.setEnabled(false);
            btnActivarCuenta.setEnabled(true);
        }
    } catch (NegocioException e) {
        JOptionPane.showMessageDialog(this, "Error al obtener el estado del médico: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    private void bajaCuenta (){
    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Estás seguro de que deseas desactivar tu cuenta?", 
        "Confirmar baja temporal", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE
    );
    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            String idUsuario = ManejadorSesion.getIdUsuario();
            int idMedico = Integer.parseInt(idUsuario);

            boolean exito = medicoBO.darDeBajaTemporal(idMedico);
            if (exito) {
                JOptionPane.showMessageDialog(this, "Médico dado de baja temporalmente correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarEstadoMedicoYActualizarBotones(); 
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo dar de baja temporalmente al médico.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al dar de baja temporalmente al médico: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Operación cancelada.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }  
    }
    
    public void activarCuenta (){
    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Estás seguro de que deseas reactivar tu cuenta?", 
        "Confirmar reactivación", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            String idUsuario = ManejadorSesion.getIdUsuario();
            int idMedico = Integer.parseInt(idUsuario);

            boolean exito = medicoBO.reactivarCuenta(idMedico);
            if (exito) {
                JOptionPane.showMessageDialog(this, "Cuenta del médico reactivada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarEstadoMedicoYActualizarBotones(); // Actualizar botones después de la operación
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo reactivar la cuenta del médico.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al reactivar la cuenta del médico: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Operación cancelada.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmCitasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmCitasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmCitasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmCitasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmCitasMedico().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarCuenta;
    private javax.swing.JButton btnAtenderCitaEmergencia;
    private javax.swing.JButton btnAtenderCitaProxima;
    private javax.swing.JButton btnBajaTemporal;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnConsultaPrevia;
    private javax.swing.JButton btnGenerarConsulta1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblCitasEmergencia;
    private javax.swing.JLabel lblCitasProximas;
    private javax.swing.JLabel lblNombreCompletoMedico;
    private javax.swing.JPanel panelBarraLateral;
    private GUI.PanelRound panelRedondoCitasE;
    private GUI.PanelRound panelRedondoCitasP;
    private javax.swing.JTable tablaCitas;
    private javax.swing.JTable tablaCitasEmergencia;
    // End of variables declaration//GEN-END:variables
}
