/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.CitaBO;
import DTO.CitaEmergenciaDTO;
import DTO.ConsultaDTO;
import configuracion.DependencyInjector;
import excepciones.NegocioException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sesion.ManejadorSesion;

/**
 *
 * @author Alici
 */
public class FrmGenerarConsulta extends javax.swing.JFrame {

    private CitaBO citaBO = DependencyInjector.crearCitaBO();

    /**
     * Creates new form FrmGenerarConsulta
     */
    public FrmGenerarConsulta() {
        initComponents();
        llenarComboEspecialidad();
        btnGenerarFolio.setEnabled(false);
        agregarListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRedondo = new GUI.PanelRound();
        lblSeleccionEspecialidad = new javax.swing.JLabel();
        cBoxEspecialidad = new javax.swing.JComboBox<>();
        btnGenerarFolio = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        lblMedicoTitulo = new javax.swing.JLabel();
        lblHoraTitulo = new javax.swing.JLabel();
        panelRedondoHora = new GUI.PanelRound();
        lblHora = new javax.swing.JLabel();
        panelRedondoMedico = new GUI.PanelRound();
        lblMedico = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblInfo2 = new javax.swing.JLabel();
        panelRedondoFolio = new GUI.PanelRound();
        lblFolio = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(241, 243, 245));
        setResizable(false);

        panelRedondo.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondo.setRoundBottomLeft(30);
        panelRedondo.setRoundBottomRight(30);
        panelRedondo.setRoundTopLeft(30);
        panelRedondo.setRoundTopRight(30);

        lblSeleccionEspecialidad.setText("Seleccione la especialidad en la que desea consultar");

        btnGenerarFolio.setBackground(new java.awt.Color(30, 98, 159));
        btnGenerarFolio.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarFolio.setText("Generar folio");
        btnGenerarFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFolioActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfo.setText("Se le ha asignado el siguiente médico y hora:");

        lblMedicoTitulo.setText("Médico:");

        lblHoraTitulo.setText("Hora:");

        panelRedondoHora.setBackground(new java.awt.Color(241, 243, 245));
        panelRedondoHora.setRoundBottomLeft(30);
        panelRedondoHora.setRoundBottomRight(30);
        panelRedondoHora.setRoundTopLeft(30);
        panelRedondoHora.setRoundTopRight(30);

        javax.swing.GroupLayout panelRedondoHoraLayout = new javax.swing.GroupLayout(panelRedondoHora);
        panelRedondoHora.setLayout(panelRedondoHoraLayout);
        panelRedondoHoraLayout.setHorizontalGroup(
            panelRedondoHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoHoraLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelRedondoHoraLayout.setVerticalGroup(
            panelRedondoHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoHoraLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblHora)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelRedondoMedico.setBackground(new java.awt.Color(241, 243, 245));
        panelRedondoMedico.setRoundBottomLeft(30);
        panelRedondoMedico.setRoundBottomRight(30);
        panelRedondoMedico.setRoundTopLeft(30);
        panelRedondoMedico.setRoundTopRight(30);

        javax.swing.GroupLayout panelRedondoMedicoLayout = new javax.swing.GroupLayout(panelRedondoMedico);
        panelRedondoMedico.setLayout(panelRedondoMedicoLayout);
        panelRedondoMedicoLayout.setHorizontalGroup(
            panelRedondoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoMedicoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRedondoMedicoLayout.setVerticalGroup(
            panelRedondoMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondoMedicoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lblMedico)
                .addGap(37, 37, 37))
        );

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flechaRegresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblInfo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfo2.setText("Su folio de atención es el siguiente:");

        panelRedondoFolio.setBackground(new java.awt.Color(128, 204, 43));
        panelRedondoFolio.setRoundBottomLeft(30);
        panelRedondoFolio.setRoundBottomRight(30);
        panelRedondoFolio.setRoundTopLeft(30);
        panelRedondoFolio.setRoundTopRight(30);

        lblFolio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFolio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRedondoFolioLayout = new javax.swing.GroupLayout(panelRedondoFolio);
        panelRedondoFolio.setLayout(panelRedondoFolioLayout);
        panelRedondoFolioLayout.setHorizontalGroup(
            panelRedondoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondoFolioLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        panelRedondoFolioLayout.setVerticalGroup(
            panelRedondoFolioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoFolioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblFolio)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lblInfo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo3.setToolTipText("");

        javax.swing.GroupLayout panelRedondoLayout = new javax.swing.GroupLayout(panelRedondo);
        panelRedondo.setLayout(panelRedondoLayout);
        panelRedondoLayout.setHorizontalGroup(
            panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRedondoLayout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(161, 161, 161)
                        .addGroup(panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRedondoFolio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInfo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblSeleccionEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRedondoLayout.createSequentialGroup()
                        .addComponent(cBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRedondoLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelRedondoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHoraTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelRedondoLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnGenerarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panelRedondoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelRedondoLayout.setVerticalGroup(
            panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGenerarFolio)
                    .addGroup(panelRedondoLayout.createSequentialGroup()
                        .addComponent(lblSeleccionEspecialidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRedondoLayout.createSequentialGroup()
                        .addGroup(panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedicoTitulo)
                            .addComponent(lblHoraTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelRedondoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRedondoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblInfo2)
                .addGroup(panelRedondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)
                        .addGap(28, 28, 28))
                    .addGroup(panelRedondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelRedondoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFolioActionPerformed
        generarFolio();
    }//GEN-LAST:event_btnGenerarFolioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmGenerarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmGenerarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmGenerarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmGenerarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmGenerarConsulta().setVisible(true);
//            }
//        });
//    }
    
    /**
    * Genera un folio para la cita de emergencia, muestra los detalles y deshabilita el botón.
    */
    private void generarFolio() {
        try {
            CitaEmergenciaDTO cita = citaBO.asignarCitaEmergencia(cBoxEspecialidad.getSelectedItem().toString(), ManejadorSesion.getIdUsuario()); //Usa el idPaciente que se manda desde la otra clase, ya no usa el manejadorsesion.
            lblMedico.setText(cita.getMedicoDTO().getNombresMedico() + " " + cita.getMedicoDTO().getApellidoPaternoMedico() + " " + cita.getMedicoDTO().getApellidoMaternoMedico());
            lblHora.setText("Fecha: " + cita.getFechaHora().toLocalDate().toString() + " Hora: " + cita.getFechaHora().toLocalTime().toString());
            lblFolio.setText(cita.getFolioCita());
            lblInfo3.setText("Su folio será valido hasta las " + cita.getFechaHora().toLocalTime().plusMinutes(10));
            btnGenerarFolio.setEnabled(false);


        } catch (NegocioException ex) {
            Logger.getLogger(FrmGenerarConsulta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
    * Agrega un listener al JComboBox de especialidades para habilitar o deshabilitar el botón de generar folio.
    */
    private void agregarListener() {
        // Listener para cBoxEspecialidad
        cBoxEspecialidad.addItemListener(e -> {
            if (cBoxEspecialidad.getSelectedIndex() != -1) {
                btnGenerarFolio.setEnabled(true);
            } else {
                btnGenerarFolio.setEnabled(false);
            }
        });

    }
    /**
     * Llena el JComboBox de especialidades con las especialidades disponibles.
     * Si no hay especialidades, lanza una excepción y muestra un mensaje de error.
     */
    private void llenarComboEspecialidad() {
        try {
            List<String> listaEspecialidades = citaBO.especialidadesMedicos();

            if (listaEspecialidades.isEmpty()) {
                throw new NegocioException("No hay especialidades disponibles");
            }
            for (String especialidad : listaEspecialidades) {
                cBoxEspecialidad.addItem(especialidad);
            }
            cBoxEspecialidad.setSelectedIndex(-1);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
    * Método para manejar el regreso al formulario de citas.
    * Si hay un folio de consulta, pregunta al usuario si desea perderlo.
    * Si el usuario acepta, cancela la cita y regresa a la pantalla de citas.
    */
    private void regresar() {

        if (lblFolio.getText().isBlank()) {
            FrmCitasPaciente frmCitasPaciente = new FrmCitasPaciente();
            frmCitasPaciente.setVisible(true);
            dispose();
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(this, "Si regresa perderá el folio de consulta, ¿Desea regresar?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0) {
            try {
                citaBO.cancelarCitaPorFolio(lblFolio.getText());
            } catch (NegocioException ex) {
                Logger.getLogger(FrmGenerarConsulta.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            FrmCitasPaciente frmCitasPaciente = new FrmCitasPaciente();
            frmCitasPaciente.setVisible(true);
            dispose();
        }
    }

    private void regresarNormal() {

        FrmCitasPaciente frmCitasPaciente = new FrmCitasPaciente();
        frmCitasPaciente.setVisible(true);
        dispose();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarFolio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cBoxEspecialidad;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHoraTitulo;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblMedicoTitulo;
    private javax.swing.JLabel lblSeleccionEspecialidad;
    private GUI.PanelRound panelRedondo;
    private GUI.PanelRound panelRedondoFolio;
    private GUI.PanelRound panelRedondoHora;
    private GUI.PanelRound panelRedondoMedico;
    // End of variables declaration//GEN-END:variables
}
